# -*- coding: utf-8 -*-
"""DIP Lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9BNDOI-cCgt7XgDP4nSMMeLVQVg1k1i
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import data
from skimage.transform import resize

from PIL import Image

img = Image.open("/content/gray.jpg").convert('L')

image = np.array(img)
image = resize(image, (512, 512), anti_aliasing=True)
image = (image * 255).astype(np.uint8)

plt.figure(figsize=(4, 4))
plt.imshow(image, cmap='gray')
plt.title("Uploaded Grayscale Image (512x512)")
plt.axis('off')
plt.show()

# Add Gaussian noise (mean=0, std=25)
noise = np.random.normal(0, 25, image.shape)
noisy_image = image.astype(np.float64) + noise
noisy_image = np.clip(noisy_image, 0, 255)

plt.figure(figsize=(4, 4))
plt.imshow(noisy_image, cmap='gray')
plt.title("Noisy Image (Gaussian Noise Added)")
plt.axis('off')
plt.tight_layout()
plt.show()

# Compute 2D FFT and shift zero-frequency to center
F = np.fft.fft2(noisy_image)
F_shift = np.fft.fftshift(F)

# Visualize magnitude spectrum
magnitude_spectrum = np.log(1 + np.abs(F_shift))

plt.figure(figsize=(4, 4))
plt.imshow(magnitude_spectrum, cmap='gray')
plt.title("Magnitude Spectrum (FFT of Noisy Image)")
plt.axis('off')
plt.tight_layout()
plt.show()

# Create meshgrid for distance from center
rows, cols = noisy_image.shape
u = np.arange(rows)
v = np.arange(cols)

u = u - rows // 2
v = v - cols // 2

V, U = np.meshgrid(v, u)
D = np.sqrt(U**2 + V**2)  # distance from center (D(u,v))

# Butterworth LPF: H(u,v) = 1 / (1 + (D/D0)^2n)
D0 = 30   # cutoff frequency
n  = 4    # filter order

H_butter = 1 / (1 + (D / D0) ** (2 * n))

# Apply filter in frequency domain
G_butter = F_shift * H_butter

# Inverse FFT to get filtered image
G_butter_ishift = np.fft.ifftshift(G_butter)
filtered_butter = np.fft.ifft2(G_butter_ishift)
filtered_butter = np.abs(filtered_butter)
filtered_butter = np.clip(filtered_butter, 0, 255)

# Visualize filter shape
plt.figure(figsize=(4, 4))
plt.imshow(H_butter, cmap='gray')
plt.title("4th Order Butterworth LPF (D0=30)")
plt.axis('off')
plt.tight_layout()
plt.show()

# Gaussian LPF: H(u,v) = exp( -D^2 / (2 * D0^2) )
D0 = 30   # cutoff frequency (same as Butterworth for fair comparison)

H_gauss = np.exp(-(D**2) / (2 * D0**2))

# Apply filter in frequency domain
G_gauss = F_shift * H_gauss

# Inverse FFT
G_gauss_ishift = np.fft.ifftshift(G_gauss)
filtered_gauss = np.fft.ifft2(G_gauss_ishift)
filtered_gauss = np.abs(filtered_gauss)
filtered_gauss = np.clip(filtered_gauss, 0, 255)

# Visualize filter shape
plt.figure(figsize=(4, 4))
plt.imshow(H_gauss, cmap='gray')
plt.title("Gaussian LPF (D0=30)")
plt.axis('off')
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 4, figsize=(18, 5))

axes[0].imshow(image, cmap='gray')
axes[0].set_title("Original")
axes[0].axis('off')

axes[1].imshow(noisy_image, cmap='gray')
axes[1].set_title("Noisy Image")
axes[1].axis('off')

axes[2].imshow(filtered_butter, cmap='gray')
axes[2].set_title("Butterworth LPF (n=4, D0=30)")
axes[2].axis('off')

axes[3].imshow(filtered_gauss, cmap='gray')
axes[3].set_title("Gaussian LPF (D0=30)")
axes[3].axis('off')

plt.suptitle("Frequency Domain Low Pass Filtering Comparison", fontsize=14)
plt.tight_layout()
plt.show()

# MSE — Mean Squared Error
mse_noisy    = np.mean((image.astype(np.float64) - noisy_image) ** 2)
mse_butter   = np.mean((image.astype(np.float64) - filtered_butter) ** 2)
mse_gauss    = np.mean((image.astype(np.float64) - filtered_gauss) ** 2)

# PSNR — Peak Signal-to-Noise Ratio
psnr_noisy   = 10 * np.log10(255**2 / mse_noisy)
psnr_butter  = 10 * np.log10(255**2 / mse_butter)
psnr_gauss   = 10 * np.log10(255**2 / mse_gauss)

print("=" * 40)
print(f"{'Image':<25} {'MSE':>8}  {'PSNR (dB)':>10}")
print("=" * 40)
print(f"{'Noisy Image':<25} {mse_noisy:>8.2f}  {psnr_noisy:>10.2f}")
print(f"{'Butterworth LPF (n=4)':<25} {mse_butter:>8.2f}  {psnr_butter:>10.2f}")
print(f"{'Gaussian LPF':<25} {mse_gauss:>8.2f}  {psnr_gauss:>10.2f}")
print("=" * 40)

